config/routes.rb
require 'sidekiq/web'
YelpAnalysis::Application.routes.draw do
  get "hadoopjob/index"
  get "hadoopjob/status"
  get "hadoopjob/data_fetched"
  mount Sidekiq::Web, at: '/sidekiq'

  root to: "hadoopjob#index"

  

end

app/models/hadoop_status.rb
class HadoopStatus < ActiveRecord::Base
end

app/models/input.rb
class Input < ActiveRecord::Base
	validates :url, presence: true
end

app/models/last_fetch.rb
class LastFetch < ActiveRecord::Base
end

app/models/output.rb
class Output < ActiveRecord::Base
  belongs_to :input
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hadoopjob_controller.rb
class HadoopjobController < ApplicationController
  def index
  	@all_inputs = Input.all
  end

  def status
  	@hadoop_status = HadoopStatus.first.nil? ? HadoopStatus.create : HadoopStatus.first
  	if @hadoop_status &&  !@hadoop_status.started && !request.xhr?
  		HadoopJobWorker.perform_async
  	end
  	respond_to do |format|
  		format.js
  		format.html
  	end
  end

  def data_fetched
  	@output_columns = Output.columns.map(&:name)
  	@output_data = Output.where('updated_at > ?',LastFetch.last.last_fetched_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hadoopjob_helper.rb
module HadoopjobHelper
  def mark_complete_hadoop_job(hadoop_status)
    hadoop_status.started = false
    hadoop_status.save
  end
end

app/views/hadoopjob/data_fetched.html.erb
<h3>Here is the list of news brought in the last run of Hadoop:</h3>

<% if @output_data.empty? %>
<div class="row-fluid center-text">
	No data fetched in the last run.
</div>
<% else %>
<table class="datatable table table-striped">
	<thead>
		<tr>
			<% @output_columns.each do |c| %>
			<td><%= c %></td>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @output_data.each do |o| %>
		<tr>
			<% @output_columns.each do |c| %>
			<td>
			<% if o.try(c).class == String %>
				<div class="large-cell" title="<%= o.try(c) %>">
					<%= o.try(c).length > 80 ? "#{o.try(c)[0,80]}..." : o.try(c) %>
				</div>
			<% else %>
				<%= o.try(c) %>
			<% end %>	
			</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
<% end %>

app/views/hadoopjob/index.html.erb
<h3>Here is the list of Yelp URLs to be processed on Hadoop</h3>
<table class="datatable table table-striped">
	<thead>
		<tr>
			<td>Name</td>
			<td>Url</td>
		</tr>
	</thead>
	<tbody>
		<% @all_inputs.each do |i| %>
		<tr>
			<td><%= i.name %></td>
			<td><%= i.url %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Start Processing' , hadoopjob_status_path, class: 'btn btn-primary' %>

app/views/hadoopjob/status.html.erb
<h3>Following is the status of Current Hadoop Job: </h3>
<h5>Running Jobs:</h5>
<div>
    <span>DB to HDFS: </span>
    <div class="loader db_loader"></div>
</div>
<div class="progress progress-success progress-striped">
    <div id="db_to_hdfs" class="bar" style="width: 0%">
        
    </div>
</div>
<br>
<div>
    <span>Fetching Yelp Data: </span>
    <div class="loader yelp_loader"></div>
</div>
<div class="progress progress-success progress-striped">
    <div id="yelp_fetcher" class="bar" style="width: 0%">
        
    </div>
</div>
<br>
<div>
    <span>HDFS to DB: </span>
    <div class="loader hdfs_loader"></div>
</div>
<div class="progress progress-success progress-striped">
    <div id="hdfs_to_db" class="bar" style="width: 0%">
        
    </div>
</div>
<br>
<form action="/hadoopjob/data_fetched">
    <button type="submit" id="check-output" class="btn btn-success" disabled>Check Output</button>
</form>
<script>
	$(function(){
       var interval = 2000;
       var error_count = 0;
       var get_status = function(){ 
           var jqxhr = $.ajax({
               url: '<%= hadoopjob_status_url %>'
           });
           jqxhr.done(function(data){
                eval(data);
                var db_to_hdfs_width = $('#db_to_hdfs').css('width');
                var yelp_fetcher_width = $('#yelp_fetcher').css('width');
                var hdfs_to_db_width = $('#hdfs_to_db').css('width');
                var progress_width = $('.progress').css('width');
                if(db_to_hdfs_width == progress_width &&  yelp_fetcher_width == progress_width && hdfs_to_db_width == progress_width){
                    console.log("hadoop job complete");
                }else{
                setTimeout(function(){
                    get_status();
                },interval);
            }
            });
           jqxhr.fail(function(error){
                alert("Sorry an error occoured, will try again in some time.");
                error_count++;
                if(error_count < 5){
                    setTimeout(function(){
                        get_status();
                    },interval);
                }
            });
        }
        get_status();
   });
</script>

app/views/hadoopjob/status.js.erb
<%if @hadoop_status.started %>
	<% if @hadoop_status.db_to_hdfs %>
		$("#db_to_hdfs").css("width","100%");
		$('.db_loader').hide();
	<% else %>
		$("#db_to_hdfs").css("width","0%");
		$('.db_loader').show();
	<% end %>
	<% if @hadoop_status.yelp_fetcher %>
		$("#yelp_fetcher").css("width","100%");
		$('.yelp_loader').hide();
	<% else %>
		$("#yelp_fetcher").css("width","0%");
		$('.yelp_loader').show();
	<% end %>
	<% if @hadoop_status.hdfs_to_db %>
		$("#hdfs_to_db").css("width","100%");
		$('.hdfs_loader').hide();
	<% else %>
		$("#hdfs_to_db").css("width","0%");
		$('.hdfs_loader').show();
	<% end %>
<% end %>
	<% if @hadoop_status.db_to_hdfs && @hadoop_status.yelp_fetcher && @hadoop_status.hdfs_to_db && @hadoop_status.started %>
		<% mark_complete_hadoop_job(@hadoop_status) %>
		$("#check-output").prop("disabled",false);
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpAnalysis</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>